### ISSUE TITLE
Two small suggestions for "Introduction to R"

### ISSUE THREAD

**Issue by linqinyu** [datacarpentry/socialsci-workshop#48]
Two small suggestions, see if this makes sense!
(1) For the part of "Functions and their arguments", it might be helpful to quickly go through different rounding functions (i.e., ceiling, floor, and trunc), after the function "round". 
(2) For the "Missing data" part, one example that might be useful & meaning to add is how to change all missing values into a particular value, such as 999.

**Comment by atheobold** [comment]
@linqinyu thank you for voicing some suggestions for the Introduction to R lesson! Currently, the lesson's exercise (that follows the introduction of `round()`) asks learners to explore the help file for round. The `ceiling()`, `floor()`, and `trunc()` functions are included in this help file, and the exercise prompts learners to look for functions that are similar to round. To me, this prompting is sufficient for introducing these additional rounding functions. 

Additionally, because `R` has many tools for working with missing data that have been coded as `NA`s, I would prefer to stick to advocating for researchers to code their data in this way. Although I have seen researchers need to recode data where missing values were coded as 999 to `NA` values, this change would not fit the context of the exploration of missing values in this section.

**Comment by linqinyu** [comment]
Makes sense to me! Thanks for the answers!
